import "./style/style.css";
import "./components/comp-navbar";
import "./components/comp-hero";
import "./components/comp-trending";
import "./components/comp-toprated";
import "./components/comp-upcoming";
import "./components/comp-popular";
import "./components/comp-footer";
import "./components/comp-backtotop";
